# image: mcr.microsoft.com/dotnet/core/sdk:3.1
image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test host
            caches:
              - dotnetcore
            script:
              - cd host
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore
              - dotnet build --no-restore --configuration Release
              - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
        # - step:
        #     name: Lint the code host
        #     caches:
        #       - dotnetcore
        #     script:
        #       - cd host
        #       - export SOLUTION_NAME=host
        #       - export REPORTS_PATH=linter-reports
        #       - dotnet new tool-manifest
        #       - dotnet tool install JetBrains.ReSharper.GlobalTools
        #       - dotnet tool restore
        #       - dotnet jb inspectcode ${SOLUTION_NAME}.sln --output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
        #     artifacts:
        #       - linter-reports/**
        #       
        # - step:
        #     name: Build and Test client
        #     caches:
        #       - dotnetcore
        #     script:
        #       - cd client
        #       - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
        #       - dotnet restore
        #       - dotnet build --no-restore --configuration Release
        #       - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
        # - step:
        #     name: Lint the code client
        #     caches:
        #       - dotnetcore
        #     script:
        #       - cd client
        #       - export SOLUTION_NAME=HelloProject
        #       - export REPORTS_PATH=linter-reports
        #       - dotnet client/ new tool-manifest
        #       - dotnet tool install JetBrains.ReSharper.GlobalTools
        #       - dotnet tool restore
        #       - dotnet jb inspectcode ${SOLUTION_NAME}.sln --output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
        #     artifacts:
        #       - linter-reports/**
